### ISSUE TITLE
ReactJS problem - Cannot read property 'componentWillEnter' of undefined

### ISSUE THREAD

**Issue by pedroposada** [SelectTransform/st.js#1]
I have tried to integrate your library in my react project and I am dealing with a problem, I think its related to your library because it only happens when I import it.

I want to use your library to parse a response from facebook, like so:

```javascript
import stjs from 'stjs'
...
.then((response) => {
  return stjs.select(response)
  .transformWith({
          '{{#each payload}}': {
            name: '{{name}}',
            fbPicture: '{{#? fbPicture.data.url}}',
            fbPageId: '{{fbPageId}}',
            fbPageLink: '{{fbPageLink}}'
          }
        })
        .root()
```

But my parent component complains when I update the state with the parsed response.

Error:
```javascript
Uncaught (in promise) TypeError: Cannot read property 'componentWillEnter' of undefined
```
Line 82 of TransitionGroup.js
```javascript
if (component.componentWillEnter) {
        component.componentWillEnter(_this._handleDoneEntering.bind(_this, key, component));
      } else {
        _this._handleDoneEntering(key, component);
      }
```

#### My Versions

"react": "^15.4.2"
"webpack": "^1.12.14"
"stjs": "0.0.3"

#### Tried the following webpack config as well with no luck
```javascript
webpackConfig.module.loaders.push(
  {
    test: require.resolve('stjs'),
    loader: 'imports-loader',
    query: {
      'JSON': '>{' +
        'stringify: window.JSON.stringify,' +
        'parse: window.JSON.parse' +
      '}',
      'this': '>null',
      'exports': '>undefined'
    }
  },
  {
    test: require.resolve('stjs'),
    loader: 'exports-loader?JSON'
  },
....
```

**Comment by gliechtenstein** [comment]
@pedroposada could you share a quick example code i can try out instantly? (maybe a repo or a zip file) Would be nice to have something that can be verified as fixed once i fix it. The simpler the example the better. Thanks!

**Comment by gliechtenstein** [comment]
@pedroposada Just noticed one thing from your code, you're using:

```
stjs.select(response)....
```

But that's how you use the library. According to the docs:

![screen shot 2017-10-18 at 12 13 50 am](https://user-images.githubusercontent.com/16613330/31705244-749556dc-b399-11e7-8245-b673ada0a15a.png)

Anyway, please try using `JSON.select` instead of `stjs.select`, as the library doesn't expose a variable named `stjs`.

If that still doesn't work, please share your code so i can try out and see what's wrong.

**Comment by gliechtenstein** [comment]
Just a heads up, because many people brought up the issue of overriding the native `JSON` object, the new version has gotten rid of the `JSON` syntax. https://github.com/SelectTransform/st.js/commit/d05ae20b336cc0f0d786b2808ad23b0f54036ff1

This means if you're using this in a browser, instead of `JSON.select`, you should use `ST.select`.

And if you're using this in a browser you can do:

```
var ST = require('st');
var parsed = ST.select(...)
```

This should get rid of the problem. Closing.
