### ISSUE TITLE
Is it possible to apply inline javascript without adding prototype methods? + Possible bug

### ISSUE THREAD

**Issue by julienben** [SelectTransform/st.js#12]
Hello!

I'm loving this tool and hoping to adopt it in a large project but am running into one major snag.

As you can see in the snippet, I can apply a function to my field if it's been added to the Number prototype. However, I can't find a way to do this without using prototype methods.

Is this something that can be done with the library as it is currently?

Possibly related: I think you have a misplaced bracket on line 483 where you're doing [types].indexOf(false) which will always return -1 (truthy).

 Thanks in advance for any help!!

```javscript
Number.prototype.formatDate = function(dateFormat) {
  return "Date formatted with " + dateFormat;
}

function formatDate(date, dateFormat) {
  return "Date formatted with " + dateFormat;
}

var template = {
  formatted: '{{date.formatDate("YYYY-MM-DD")}}',            // WORKS
  formatted2: '{{formatDate(date, "YYYY-MM-DD")}}',    // DOESNT WORK
};

var data = {
  date: 1510753729541,
};

ST.select(data).transformWith(template).root()
```

**Comment by julienben** [comment]
UPDATE:

It turns out there was an error at line 498 (`var evaluated = func();`) because formatDate was undefined in this block. I "fixed" it by adding the formatDate function to the global scope.

This can be fixed for real by not wrapping ST in an anonymous function. I think this is the way to go. LMK if you are open to PRs.

**Comment by gliechtenstein** [comment]
@julienben Thanks for the heads up. I just realized that I haven't documented one method that can help with this situation. It's called [inject](https://github.com/SelectTransform/st.js/blob/develop/st.js#L188)

It lets you declare a global variable and inject it into ST context so you can do what you were trying to do. For example, the following works:

```
var ST = require("stjs");
Number.prototype.formatDate = function(dateFormat) {
  return "Date formatted with " + dateFormat;
}

global.formatDate = function(date, dateFormat) {
  return "Date formatted with " + dateFormat;
}

var template = {
  formatted: '{{date.formatDate("YYYY-MM-DD")}}',            // WORKS
  formatted2: '{{formatDate(date, "YYYY-MM-DD")}}',    // DOESNT WORK
};

var data = {
  date: 1510753729541,
};

var res = ST.select(data).inject(["formatDate"]).transformWith(template).root()
```

The `inject` method lets you specify an array of global variable names, and it injects it into ST context.

A couple of things to be aware of:

1. You must declare the variable a global variable. On a browser context you can simply do `var formatDate` but in Node.js environment you need to do `global.formatDate` (You can see this in action above)
2. Currently, the inject method takes an array of **variable names** (instead of actual variable objects). This was because I tried to make this cross platform (as in, you can use this not just on the web or node environment, but also on iOS and Android). By passing the variables as a name string instead of the actual reference of the variable, I got around the limitation of having to already have a reference to the injecting javascript variables when calling `ST` methods.

That said, if you would like to poke around and come up with another API that can inject variables into ST by reference, feel free to make a suggestion. I think it makes sense as long as it's consistent with rest of the syntax.

**Comment by julienben** [comment]
Hey @gliechtenstein,

Thanks for your detailed response!

What's the purpose of the inject though?

Once you've added the function to the global scope, it's available inside ST. In other words, the sample you just wrote works equally well if you remove `.inject(["formatDate"])`.

**Comment by julienben** [comment]
Check it out by pasting this on the left side of the playground tool:
```javascript
window.formatDate = function(date, dateFormat) {
  return "Date formatted with " + dateFormat;
}

var template = {
  formatted: '{{formatDate(date, "YYYY-MM-DD")}}',
};

var data = {
  date: 1510753729541,
};
```
(Just replaced `global` with `window` for browser setting.)

**Comment by gliechtenstein** [comment]
You're right! I can't remember why I did it this way, but I just updated the code to take an injection object as an argument instead of a string array: https://github.com/SelectTransform/st.js/commit/56eb4d262bc50a10eda2e0f75268ef6d10f3eee5

This gets rid of the need to use the global variable, as can be seen here: https://github.com/SelectTransform/st.js/blob/develop/test/unit/transform/inject.js#L25

What do you think? I just updated the npm version to [0.0.5](https://github.com/SelectTransform/st.js/blob/develop/package.json#L3) so running another `npm install` should update the library, please try it out and let me know.

**Comment by gliechtenstein** [comment]
I think this issue has been addressed, so closing. Please feel free to reopen if i missed something.
