### ISSUE TITLE
Development moved to https://github.com/jasonelle/jasonelle

### ISSUE THREAD

**Issue by clsource** [SelectTransform/st.js#29]
https://github.com/jasonelle/jasonelle
will continue ST legacy. Issues and pull request would be slowly tackled in the other repo

**Comment by JakubMifek** [comment]
Hi @clsource 
It seems that there are several people maintaining the module right now, you, me and @mpanichella.
I use it only for backend purposes and rewrote it to easily extendable typescript module here: https://github.com/JakubMifek/SelectTransform/
It would be great if we somehow managed to combine our forces instead of separating them.

**Comment by clsource** [comment]
Hi @JakubMifek I wasn´t aware that other people were maintaining this code. Sure a new Github organization can be created to store a centralized version of st.js since _Jasonelle_ is mainly maintaining _Jasonette mobile_ and it would be much clean and easier to just redirect to a new location for st.js.

**Comment by JakubMifek** [comment]
Me neither until now. :smile: I totally forgot to somehow regularly check issues in this repository and/or create issue of my own that states what I did like you two :slightly_smiling_face: 

I do not develop FE applications and have no idea whether you are capable of including typescript module - originally the module was single JS file which in my solution it is no more. Does it raise issues for your application?

Also, how much effort are you willing to invest into the module? Would you rather let someone else maintain it and just make demands to it if you need any changes or would you prefer active participation in development and maintenance?

**Comment by clsource** [comment]
I made a fork just to fix issues regarding st.js in mobile environments. But no issues that I am aware of was rised since the fork, so I prefer to be an user to st.js that could test the lib in mobile environments.

The requirements for mobile are the same as a browser with ES6 capabilities. So the lib must have a minified bundle maybe using http://browserify.org/  with a single file that I could import using simple `<script src="st.js" type="text/javascript">` tags.

**Comment by JakubMifek** [comment]
> I made a fork just to fix issues regarding st.js in mobile environments. But no issues that I am aware of was rised since the fork, so I prefer to be an user to st.js that could test the lib in mobile environments.

No problem :)

> The requirements for mobile are the same as a browser with ES6 capabilities. So the lib must have a minified bundle maybe using http://browserify.org/ with a single file that I could import using simple <script src="st.js" type="text/javascript"> tags.

I made the [bundle](https://github.com/JakubMifek/SelectTransform/blob/master/st.js). I didn't have time to create some proper tests yet, but feel free to test it if you will.

Beware though that I changed the interface a bit and extended functionalities. The main difference is that I execute the transformation asynchronously and return a `Promise` instance. However, I kept original synchronous execution under `transformSync`. ST.js functions are named the same way and there are few new ones. Documenting in progress :))

Also I'm not sure about integration to browser's global context. I tried to somehow copy idea from the original code and am assigning instance of `SelectTransform` class to `ST` parameter of `$context` global variable. I will have to study up how to test scenarios where the variable I am assigning to is not defined (Jest does not seem to like it even if I try to create the `$context` as global variable before import).

**Comment by mpanichella** [comment]
Hi!, of course, i want to work with this project, do you think if we take the project to a common repository ?, that allows people to access and help, in the same way that it is today with SelectTransform?, On the other hand, what you said, currently I am working with st.js, because I am using st.js with the WSO2 tool, using it with nashorn, (Javascript inside the java virtual machine), it is for this reason that I need it to be in a single file, in addition to working with ECMA5

**Comment by mpanichella** [comment]
> Hi @clsource
> It seems that there are several people maintaining the module right now, you, me and @mpanichella.
> I use it only for backend purposes and rewrote it to easily extendable typescript module here: https://github.com/JakubMifek/SelectTransform/
> It would be great if we somehow managed to combine our forces instead of separating them.

Hi!, of course, i want to work with this project, do you think if we take the project to a common repository ?, that allows people to access and help, in the same way that it is today with SelectTransform?, On the other hand, what you said, currently I am working with st.js, because I am using st.js with the WSO2 tool, using it with nashorn, (Javascript inside the java virtual machine), it is for this reason that I need it to be in a single file, in addition to working with ECMA5

**Comment by JakubMifek** [comment]
Hi @mpanichella, sorry for taking so long to answer.

> do you think if we take the project to a common repository ?

Sure, if you are interested in active cooperation, I have no problem with that.

> I need it to be in a single file, in addition to working with ECMA5

I believe the single file that I included in the repository recently for clsource should meet ECMA5. Would you mind testing in your project whether it is applicable?

**Comment by clsource** [comment]
I think this tool can help standarize the codebase https://github.com/developit/microbundle and tailor it for different ecosystems
