### ISSUE TITLE
Function call

### ISSUE THREAD

**Issue by paulogr** [SelectTransform/st.js#8]
Is that possible to call a function from the template ?

The example bellow isn't working for me

```

function timestamp(date) {
  return new Date(date).getTime()
}

JSON.select({ date: '2016-10-23' }).transformWith({
  created_at: '{{ timestamp(date) }}'
})

```

Thank you!

**Comment by gliechtenstein** [comment]
That's because you're not selecting the `timestamp` function as data to be parsed with the template.

It should look like this:

```
function timestamp(date) {
  return new Date(date).getTime()
}

var res = JSON.select({ date: '2016-10-23', timestamp: timestamp }).transformWith({
  created_at: '{{ timestamp(date) }}'
}).root();
```

Note that you must call `root()` to get the final result. Otherwise you'll end up with the entire selection object.

You can check out the functional code [here](https://jsfiddle.net/bLfcosrf)

---

A simpler version (that I may not have documented) is simply calling `JSON.transform(template, data)`, which looks like:

```
function timestamp(date) {
  return new Date(date).getTime()
}

var res = JSON.transform({
  created_at: "{{timestamp(date)}}"
}, {
  date: '2016-10-23', timestamp: timestamp
})
```

Note that in this case you didn't have to call `root()` since it's a simplified version

Check out the functional code [here](https://jsfiddle.net/bLfcosrf/1/)

**Comment by paulogr** [comment]
Great! Thank you for that information and congrats for this lib!
